### ISSUE TITLE
running from locations other than c:

### ISSUE THREAD

**Issue by Elite-IGAU** [Xjph/EliteObservatory#10]
I moved the .exe from C:\Users\My_User_Name\Downloads to D:\apps

EliteObservatory stalls at startup.  

Move back to my "Downloads" folder, starts right up.

**Comment by Xjph** [comment]
Odd, no issues at all using the same path for me.
![image](https://user-images.githubusercontent.com/455726/68209580-42b41000-ffae-11e9-9086-698137242261.png)

Can you be more specific about when this "stall" happens? Can you not push any buttons? Does the window not fully initialize? Do you have any application errors reported in the windows event log?

**Comment by Elite-IGAU** [comment]
The application shows up in windows taskbar, however no actual application window is drawn. 

When I hover over the taskbar button for the application, the "preview" pop up is a blank box. 

No data in windows event log.  Is there a command line option I can pass to the executable to get you more info?

**Comment by Xjph** [comment]
There are no command line options, though you can try wiping out any existing configuration in `%localappdata%\Observatory`. Config is stored per-location, so it working in one place fine and not another would be expected behaviour if a config went bad for some reason. 

Come to think of it, if the window startup location went weird you'd be the second person in as many weeks to have the startup location be somewhere off-screen. If that's the case you should be able to edit the config file by hand back to something sensible. I should also consider adding some kind of sanity check on startup for the window location and size properties.

**Comment by Elite-IGAU** [comment]
Wiping the config files fixed the issue, came right up. Thanks!
