### ISSUE TITLE
Coordinates X Y not visible

### ISSUE THREAD

**Issue by 3navis** [Xjph/EliteObservatory#12]
Hi,
I can only display the application when maximized.
it's as if it were outside the screen visible zone
where Obsevatory's coordinates x y height and width are stored
regards

**Comment by Xjph** [comment]
The config file should be in `%localappdata%\Observatory\`. You can either delete what's there to reset to default, or find your current user.config and hand edit the WindowLocation values to something reasonable.
You may also be able to use the windows key + left/right arrow to "snap" it to one side of your monitor while it has focus and grab it that way.

That said, I need to add some kind of sanity check to the window location when it initially loads. I meant to do it in the last update and it slipped my mind. Going to assign this issue so that I don't forget again.

**Comment by 3navis** [comment]
thanks, I found the file user.config
although the file is deleted the new has the same problem
![image](https://user-images.githubusercontent.com/37496617/68943921-d6ef5580-07ac-11ea-9345-5f7db23f0036.png)

I have modified it manually and it works
![image](https://user-images.githubusercontent.com/37496617/68943999-0605c700-07ad-11ea-998c-7af361f79e06.png)

Regards

**Comment by 3navis** [comment]
This is an example of the file that is created after deleting the previous one
(I have changed the type to attach it)
[user.txt](https://github.com/Xjph/EliteObservatory/files/3851523/user.txt)

**Comment by Xjph** [comment]
Fixed in commit 7154f21. Will see it in next release.
