### ISSUE TITLE
Have to select journal location every launch

### ISSUE THREAD

**Issue by Slegnor** [Xjph/EliteObservatory#21]
Hi, is it normal/intended that the journal location has to be set every time the program is launched?

**Comment by Xjph** [comment]
It is not. Kind of.

I added the manual folder selection as a fallback in case the usual journal location couldn't be found for some reason. If it works properly it shouldn't ask _at all_, but if it can't find your journal then yes, it will ask every time.

I'll make a change so that when you manually select a folder it will save that location so that it stops asking again.

That said, might I ask what your setup is that your journals can't be found in `%userprofile%\Saved Games\Frontier Developments\Elite Dangerous`?

**Comment by Slegnor** [comment]
That's the thing, they are located in %userprofile%\Saved Games\Frontier
Developments\Elite Dangerous

The only thing that is different is my docs folder is on D: (D:\My
Documents\Saved Games\Frontier Developments\Elite Dangerous)
if I use the %userprofile%\Saved Games\Frontier Developments\Elite
Dangerous path in Explorer it goes straight to the folder no problem

**Comment by Xjph** [comment]
Odd, the check for journal location happens here: https://github.com/Xjph/EliteObservatory/blob/4a2837fe015a35640e8c09cf02ee7e2622d9502f/Observatory/LogMonitor.cs#L134-L135

There must be something different about how `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` resolves as compared to the `%userprofile%` alias in explorer. Regardless, I'll have the path you select start saving so that worst case you're only asked once.

**Comment by Slegnor** [comment]
I had a quick look online and potentially Environment.GetEnvironmentVariable("userprofile") might be an option?
https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?redirectedfrom=MSDN&view=netframework-4.8#System_Environment_GetEnvironmentVariable_System_String_

**Comment by Gimi1967** [comment]
> That said, might I ask what your setup is that your journals can't be found in `%userprofile%\Saved Games\Frontier Developments\Elite Dangerous`?

I run all third part apps on a separate computer, accessing the journals over my LAN. Setting journal location manually is an option I would appreciate very much.

**Comment by Xjph** [comment]
Non-standard journal locations are now remembered as of d590592fa38cf677319a58446379eb5298be80dc. Should release soon.
